name: Build for linux

on:
  workflow_dispatch:

jobs:
  linux:
   name: Setup
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v3
     with:
          fetch-depth: 0
          submodules: recursive
   - uses: actions/checkout@v3
   - uses: actions/setup-java@v3
     with:
      distribution: 'zulu' # See 'Supported distributions' for available options
      java-version: '8'
   - run: | 
           sudo apt remove containerd -y
           sudo apt purge containerd.io -y
           sudo apt update
           sudo apt install docker.io -y
           mkdir build
           docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
           docker build --build-arg BASE_IMAGE=32bit/buntu:16.04 -t 32bit/ubuntu:16.04 -f Dockerfile.i386 .

   - name: Docker Work
     run: |
       docker run --rm \
          -v /home/runner/work/xash3d/xash3d:/app \
          32bit/ubuntu:16.04 \
          bash -c "cd /app && apt update && apt install cmake make gcc g++ libfontconfig1-dev libfreetype6-dev libstdc++6 libunwind-dev libsdl2-dev -y && git clone https://github.com/FWGS/vgui-dev hlsdk/ && cd build && cmake .. -DXASH_SDL=yes -DXASH_VGUI=yes -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -DCMAKE_EXE_LINKER_FLAGS=-m32 -DHL_SDK_DIR=../hlsdk && make ; rm -rf engine/c* ; rm -rf engine/C* ; rm -rf engine/Makefile ; find . -type f -name \*.so -exec mv -v {} ./engine/ \;"
     
   - name: Upload artifacts
     uses: actions/upload-artifact@v4
     with:
          name: compiled
          path: build/engine/
